### ISSUE TITLE
Why is a property sometimes returned as "" instead of null?

### ISSUE THREAD

**Issue by BowlOfSoup** [BowlOfSoup/NormalizerBundle#11]
To investigate.

**Comment by BowlOfSoup** [comment]
Unit tested OK and merged.

**Comment by raymondschouten** [comment]
The change merged for this story is a breaking change. "empty"-evaluated values like `0`, `""`, `false`, `array()` are now being normalized to `null`. Therefore the fix needs to be reverted and the issue has to be reopened.

The question also rises if `""` is wrongly outputted for `null` values, or that `""` had to be normalized to `null`, where the latter is wrong in my opinion, as `""` can be a perfectly valid value for a property, while `null` means the total absent of a value.

**Comment by BowlOfSoup** [comment]
Ok let's do this, and fix this properly. Mind that this issue was already detected a while ago.

The reason to output values to `null` instead of `""` was that for API purposes `""` can as well be `null`, like 'no value', 'nothing', 'nada', 'empty'.

But to make a suggestion to reopen this issue:

- if a property is explicit **null**, json `null` must be returned.
- If a property without `type='collection'` or `type='object'` is **empty**, json `""` must be returned.
- If a `type='collection'` is **empty**, json `[]` must be returned.
- if a `type='object'` is **empty**, json `null` must be returned.

Also, my suggestion is to make a new 1.0.* version.

**Comment by raymondschouten** [comment]
> If a property without type='collection' or type='object' is empty, json "" must be returned.

This particular rule introduces this exact issue. A property which is not a collection/object with an **empty** value will be returned as `null` because of it. For example a slider that goes from -5 to 5 (nullable integer field) which is configured at `0` will be normalized to `null`, while `null` could mean that it hasn't been configured at all.

**Comment by BowlOfSoup** [comment]
Version 3.0 was released. I don't see any occurrences anymore of the "" instead of null. Also https://github.com/BowlOfSoup/NormalizerBundle/issues/11#issuecomment-316348173 does not seem to occur, except `[]` seems to be outputted as `null`.
