### ISSUE TITLE
Can't use callback together with type="datetime"

### ISSUE THREAD

**Issue by raymondschouten** [BowlOfSoup/NormalizerBundle#12]
I have a callback method that returns a `DateTime` object, which I'd like to normalize to specific formats on different places. Therefore I'd like to use:

`@Bos\Normalize(type="datetime", format="Y-m-d", callback="getCalculatedDate")`

But this completely ignores the callback method.

In my opinion the callback method must only act as an alternative source for the property data and not influence any other functionality.

**Comment by BowlOfSoup** [comment]
@raymondschouten If you want to normalize to specific formats why not make a distinction in groups?

`@Bos\Normalize(group="date-format-1", type="datetime", format="Y-m-d")`
`@Bos\Normalize(group="date-format-2", type="datetime", format="Y")`

**Comment by raymondschouten** [comment]
Because that requires you to have a property with a DateTime object, but I don't have such a property but a method returning a calcalated DateTime object, hence the request to use _callbacks_ with type="datetime".

This can also be "solved" by being able to add the normalizer tags to methods...

**Comment by BowlOfSoup** [comment]
Then we should rather implement annotation support for methods?

**Comment by raymondschouten** [comment]
In my situation, that would be the best option. But then you should remove the callback-attribute from the property annotation. If you won't do that, the problem this issue describes is still effective: callback ignored in case of type="datetime".

**Comment by BowlOfSoup** [comment]
Improvement will be made in #15
