### ISSUE TITLE
Callback not working correctly on nested objects

### ISSUE THREAD

**Issue by raymondschouten** [BowlOfSoup/NormalizerBundle#8]
Whenever I add a normalize annotation on a nested object, the property suddenly requires a getter() method to be set, while it actually uses the specified callback.

```php
<?php

namespace AppBundle\Entity\Invoice;

use BowlOfSoup\NormalizerBundle\Annotation as Bos;

class Invoice
{
    /** @Bos\Normalize(type="object") */
    protected $debtor;
}
```

```php
<?php

namespace AppBundle\Entity\Debtor;

use BowlOfSoup\NormalizerBundle\Annotation as Bos;

class Debtor
{
    /** @Bos\Normalize(callback="getFullName", name="name") */
    protected $bosName;

    public function getFullName()
    {
        ...
    }
}
```

The following results in exception 'Exception' with message 'Unable to get property value. No get() method found for property bosName' in /full/path/to/vendor/bowlofsoup/normalizer-bundle/Service/PropertyExtractor.php:77

Whenever I add a dummy method called `getBosName`, it works. The same setup however does work on the main object...

**Comment by BowlOfSoup** [comment]
This also happens when having a callback on a:

    type="datetime"

Fix is to check if a callback has been set, this always has priority over trying to get the value trough a get method.

**Comment by BowlOfSoup** [comment]
Unit tested OK and merged.
